version: 2

# Defining default values for all jobs
defaults: &defaults
    docker:
        - image: circleci/node:lts-browsers

jobs:
    setup_tooling:
        <<: *defaults
        steps:
            - checkout
            # - Install npm dependencies for LWC linting and testing
            - run:
                  name: Install package dependencies
                  command: |
                      yarn install
            - persist_to_workspace:
                  # This is an important step. If we don't store the project data (cloned GitHub source and node_modules)
                  # we'd have to re-run installation for every workflow step.
                  root: ~/
                  paths:
                      - project/*
    prettier_verify:
        # This verifies Prettier formatting
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Verify Prettier formatting
                  command: |
                      yarn prettier:verify
    lint_lwc:
        # This lints Lightning Web Components.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Lint Lightning Web Components
                  command: |
                      yarn lint
    unit_test_lwc:
        # This unit tests Lightning Web Components.
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Unit test Lightning Web Components
                  command: |
                      yarn test:unit:coverage --runInBand
            - persist_to_workspace:
                  # We're saving the generated coverage results (folder 'coverage', a sub-folder to 'project') so
                  # that we can upload them in another step to Codecov.io.
                  root: ~/
                  paths:
                      - project/*
    upload_code_coverage:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/
            - run:
                  name: Push to Codecov.io
                  command: |
                      # Uploading LWC tests
                      bash <(curl -s https://codecov.io/bash)

workflows:
    version: 2
    build_and_test:
        jobs:
            - setup_tooling
            - prettier_verify:
                  requires:
                      - setup_tooling
            - lint_lwc:
                  requires:
                      - prettier_verify
            - unit_test_lwc:
                  requires:
                      - lint_lwc
            - upload_code_coverage:
                  requires:
                      - unit_test_lwc
